---
settings:
  name: BlueXP volume caching
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXPのボリュームキャッシュドキュメント
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - section: support
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: BlueXPのすべてのマニュアル
