---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, bluexp volume caching 
summary: ボリュームキャッシングは、リモートの場所にある書き込み可能な永続的ボリュームを提供します。BlueXPのボリュームキャッシュを使用すると、データへのアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィックをオフロードしたりできます。キャッシュボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合に、読み取り処理が大量に発生するワークロードに最適です。 
---
= キャッシュを管理します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キャッシュの編集、エクスポートポリシーの変更、キャッシュのサイズ変更、およびキャッシュの削除を行うことができます。

BlueXPのボリュームキャッシングを使用すると、次のような目的を達成できます。

* キャッシュの詳細を表示します。
* キャッシュに別のエクスポートポリシーを割り当てます。
* ボリュームのキャッシュを編集し、サイズなどを変更します Editには、他のプロパティを表示および変更するオプションがあり、今後のリリースでは、さらに多くのプロパティが編集に追加される予定です。
* 元のボリュームサイズに対する割合に基づいて既存のキャッシュのサイズを変更します。
* キャッシュを削除します。




== キャッシュの詳細を表示します

キャッシュごとに、元のボリューム、作業環境、キャッシュボリュームなどを確認できます。

.手順
. BlueXPの左側のナビゲーションで、*[モビリティ]*>*[ボリュームキャッシュ]*を選択します。
+
デスティネーション環境で作成されたキャッシュボリュームのリストを表示できます。キャッシュのリストにキャッシュの詳細が表示されます。

. リストをフィルタするには、*[+*でフィルタ]オプションを選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. [詳細の表示と編集]*を選択します。
. 詳細を確認します。




== キャッシュの編集

キャッシュの名前、ボリュームサイズ、およびエクスポートポリシーを変更できます。

.手順
. BlueXPの左側のナビゲーションで、*[モビリティ]*>*[ボリュームキャッシュ]*を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. [詳細の表示と編集]*を選択します。
. [基本設定]タブで、必要に応じてキャッシュ名とキャッシュボリュームサイズを変更します。
. 必要に応じて、[キャッシュアクセス]タブを展開し、次の値を変更します。
+
.. マウントパス。
.. 既存のエクスポートポリシーとは異なるポリシー。


. SMB / CIFS共有の詳細またはエクスポートポリシールールを変更するには、該当するオプションをクリックしてBlueXP System Managerにアクセスします。
. [ 保存（ Save ） ] を選択します。




== 別のキャッシュエクスポートポリシーを割り当ててください

キャッシュには別のエクスポートポリシーを割り当てることができます。

ソースのエクスポートポリシールールがターゲットクラスタに適用されている必要があります。


TIP: 既存のエクスポートポリシーをキャッシュに割り当てることができます。エクスポートポリシールールは変更できません。エクスポートポリシーを変更する必要がある場合は、NetAppシステムマネージャを使用できます。

.手順
. BlueXPの左側のナビゲーションで、*[モビリティ]*>*[ボリュームキャッシュ]*を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. [エクスポートポリシーの変更]*を選択します。
. キャッシュに割り当てるエクスポートポリシーを選択します。
. [ 保存（ Save ） ] を選択します。




== キャッシュのサイズ変更

キャッシュボリュームのサイズはソースボリュームの割合に基づいて変更できます。

.手順
. BlueXPの左側のナビゲーションで、*[モビリティ]*>*[ボリュームキャッシュ]*を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. [サイズ変更]*を選択します。
. 元のボリュームサイズの新しいパーセンテージを入力します。
+
キャッシュボリュームのサイズが新しい割合に変更されます。

. [ 保存（ Save ） ] を選択します。




== キャッシュを削除します

キャッシュが不要になった場合は、削除できます。これにより、ボリュームキャッシュ関係とターゲットボリュームキャッシュが削除されます。

.手順
. BlueXPの左側のナビゲーションで、*[モビリティ]*>*[ボリュームキャッシュ]*を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. 「 * 削除」を選択します。
. チェックボックスをオンにします。
. 「 * 削除」を選択します。

