---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how bluexp volume caching works, what is volume caching, bluexp 
summary: ボリュームキャッシングは、リモートの場所にある書き込み可能な永続的ボリュームを提供します。BlueXPのボリュームキャッシュを使用すると、データへのアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィックをオフロードしたりできます。キャッシュボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合に、読み取り処理が大量に発生するワークロードに最適です。 
---
= BlueXPのボリュームキャッシュについて説明します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9ソフトウェアの機能であるボリュームキャッシングは、ファイル配信を簡易化し、ユーザやコンピューティングリソースの近くにリソースを配置することでWANレイテンシを低減し、WAN帯域幅のコストを削減するリモートキャッシング機能です。ボリュームキャッシングは、リモートの場所にある書き込み可能な永続的ボリュームを提供します。BlueXPのボリュームキャッシュを使用すると、データへのアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィックをオフロードしたりできます。キャッシュボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合に、読み取り処理が大量に発生するワークロードに最適です。

BlueXPボリュームキャッシングを使用すると、特にAmazon FSx for NetApp ONTAP、Cloud Volumes ONTAP、オンプレミスの作業環境向けに、クラウド向けのキャッシュ機能を利用できます。

また、ブランチオフィスから企業のデータセットにアクセスすることもできます。クラスタ内の複数のコントローラから頻繁にアクセスする必要がある_hot data_データを提供することで、主要なアプリケーションのパフォーマンスを向上させることができます。また、ホットデータを世界中の複数の場所のユーザに対してローカルにキャッシュすることで、一元化されたデータセットへの同時アクセスを可能にし、ホットデータへのアクセス時の応答時間を短縮することで、コラボレーションを強化できます。

BlueXPボリュームキャッシングは、AWS CloudFrontが提供するAmazon S3バケットに導入されます。



== キャッシュとは

キャッシュは、ホストとデータソースの間にある一時的なストレージの場所です。キャッシュの目的は、ソースデータからデータをフェッチするよりも高速にデータを提供できるように、ソースデータの頻繁にアクセスされる部分を格納することです。キャッシュは、データが複数回アクセスされ、複数のホストで共有される読み取り処理の多い環境で最も効果的です。キャッシュシステムは、データソースを使用するシステムよりも高速です。高速なストレージシステムでキャッシュストレージスペースをホストに近接させることで実現されます。



== BlueXPのボリュームキャッシュを使用するメリット

BlueXPのボリュームキャッシュには、次のようなメリットがあります。

* ハイブリッドクラウドインフラのパフォーマンスを向上
* クラウドプロバイダ間でデータをキャッシュすることで、クラウドサイロを解消します
* ストレージコストを削減
* 地理的に離れた場所でのコラボレーション
* BlueXPでネットアップが管理するサービスを使用
* 変化するIT環境への迅速な対応
* クラウドでホストされるオンデマンドまたはサブスクリプションベースのボリュームキャッシュ




== BlueXPボリュームキャッシュの機能

BlueXPのボリュームキャッシュでは、いくつかのNetAppテクノロジをフルに活用して次のような目的を達成できます。

BlueXPのボリュームキャッシュサービスでは、いくつかのNetAppテクノロジをフルに活用して次のような目標を達成できます。

* あるクラウドプロバイダから別のクラウドプロバイダにデータをキャッシュします
* キャッシュエクスポートポリシーを表示および編集します
* 既存のキャッシュのサイズを変更します
* キャッシュを削除します




== コスト

NetAppでは、BlueXPボリュームキャッシュサービスの使用料金は請求されませんが、該当するデータの入出力料金については、クラウドプロバイダで確認する必要があります。



== ライセンス

BlueXPのボリュームキャッシングに特別なONTAPライセンスは必要ありません。



== BlueXPのボリュームキャッシュの仕組み

キャッシュボリュームは、ソースボリュームから作成される、空き領域を含むボリュームです。キャッシュボリュームは、ソースボリュームと同じクラスタにも別のクラスタにも配置できます。

キャッシュボリュームはソースボリュームのデータへのアクセスを提供しますが、すべてのデータがキャッシュボリューム内にある必要はありません。キャッシングボリュームのデータストレージは、ホットデータ（稼働中のデータ、または最近使用したデータ）のみを保持することで効率的に管理されます。

BlueXPのボリュームキャッシュは、クライアントから要求されたデータがキャッシュボリュームに含まれている場合に読み取り要求を読み取ります。それ以外の場合は、ボリュームキャッシングサービスによってソースボリュームからデータが要求され、クライアント要求を処理する前にデータが格納されます。以降のデータ要求はキャッシュボリュームから直接提供されます。初回の要求後は、データをネットワーク経由で転送したり、負荷の高いシステムから提供したりする必要がなくなるため、同じデータへのアクセスが繰り返し発生する場合のパフォーマンスが向上します。
