---
sidebar: sidebar 
permalink: release-notes/cache-limitations.html 
keywords: volume caching, bluexp 
summary: ここでは、このリリースのサービスでサポートされていない、またはサービスと正常に相互運用できないプラットフォーム、デバイス、または機能について説明します。 
---
= 既知の制限事項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、このリリースのサービスでサポートされていない、またはサービスと正常に相互運用できないプラットフォーム、デバイス、または機能について説明します。



== キャッシュエクスポートポリシールールのコピーに関する制限事項

次の場合、キャッシュエクスポートポリシールールはキャッシュボリュームにコピーされません。

* ソースボリュームの作業環境がAmazon FSx for NetApp ONTAPまたはCloud Volumes ONTAPで、キャッシュボリュームがONTAP 9.10.1以前の場合。
* ソースボリュームの作業環境がいずれかのバージョンのONTAPで、キャッシュボリュームがONTAP 9.10.1以前の場合。


回避策：キャッシュボリュームのルールは手動で作成する必要があります。



== 同じ名前のStorage VMでキャッシュの作成が失敗する

ソースクラスタとデスティネーションクラスタで同じ名前のStorage VMが使用されている場合、キャッシュは作成されません。

回避策：ソースとデスティネーションのStorage VMには異なる名前を使用します。



== 新規または最近編集したエクスポートポリシーが表示されない

キャッシュを作成するときに、最近作成または編集したエクスポートポリシーがリストに表示されないことがあります。

回避策：数分で再試行してください。



== デスティネーションでCIFSプロトコルしか有効になっていない場合、キャッシュの作成が失敗します

ソースクラスタまたはデスティネーションクラスタでONTAP 9.10.1以前が有効になっていて、デスティネーションクラスタでCIFSプロトコルしか有効になっていない場合、キャッシュの作成が失敗します。

回避策：ONTAP 9.11.1以降を実行しているデスティネーションクラスタ、またはCIFSプロトコルとNFSプロトコルの両方が設定されているデスティネーションクラスタを使用します。
